start-at-login = true
after-login-command = []
after-startup-command = []

# Don't change unless you know what you doing
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Layout & Orientation
accordion-padding = 40
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

# Auto-move mouse to focused monitor/window
on-focus-changed = ['move-mouse window-lazy-center']

# macOS Hidden Apps
automatically-unhide-macos-hidden-apps = false

# Gaps Configuration
[gaps]
inner = { horizontal = 10, vertical = 10 }
outer = { left = 5, bottom = 5, top = 5, right = 5 }

# Main Bindings
[mode.main.binding]
alt-shift-space = 'layout floating tiling'
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'
# Application Shortcuts
alt-g = 'exec-and-forget open -a /Applications/Ghostty.app'
alt-a = 'exec-and-forget open -a /Applications/Arc.app'
alt-c = 'exec-and-forget open -a /Applications/ChatGPT.app'
# Layout Switching
alt-f = 'fullscreen'
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
# Window Focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
# Move Windows
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'
# Workspaces
alt-e = 'workspace E'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-shift-e = 'move-node-to-workspace E'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
# Workspace Navigation
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-r = 'mode resize'
alt-shift-semicolon = 'mode service'

[mode.resize.binding]
esc = 'mode main'
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
b = ['balance-sizes', 'mode main']

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

# Automatic Window Assignment
[[on-window-detected]]
if.app-name-regex-substring = 'wezterm|kitty|ghostty'
run = 'move-node-to-workspace G'

[[on-window-detected]]
if.app-name-regex-substring = 'arc'
run = 'move-node-to-workspace A'

[[on-window-detected]]
if.app-name-regex-substring = 'spotify'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'move-node-to-workspace E'
