require("full-border"):setup()
require("git"):setup()
require("yatline"):setup(0, require("yatline-catppuccin"):setup("mocha"))
require("yatline-githead"):setup()
require("relative-motions"):setup({ show_numbers = "relative_absolute", show_motion = true })
