[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"

[[mgr.prepend_keymap]]
on = "F"
run = "plugin smart-filter"

[[mgr.prepend_keymap]]
on = "H"
run = "plugin bypass reverse"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin bypass smart-enter"
