set  -g base-index      1
setw -g pane-base-index 1

set -g mode-keys   vi

# rebind main key: C-a
unbind C-b
set -g prefix C-a
bind -n -N "Send the prefix key through to the application" \
  C-a send-prefix

bind-key -N "Kill the current window" & kill-window
bind-key -N "Kill the current pane" x kill-pane

# ============================================= #
# Load plugins with tpm                         #
# --------------------------------------------- #

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'fabioluciano/tmux-powerkit'
set -g @powerkit_plugins "datetime,battery,cpu,memory,git,hostname"
set -g @powerkit_theme "catppuccin"
set -g @powerkit_theme_variant "mocha"

set -g @plugin 'Morantron/tmux-fingers'

# ============================================= #

set -ga terminal-overrides ",*:Tc"

bind-key "s" run-shell "sesh connect \"$(
  sesh list --icons | fzf --tmux 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list --icons -t)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list --icons -c)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list --icons -z)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}' \
    -- --ansi
)\""

run '~/.tmux/plugins/tpm/tpm'
