accordion-padding = 30
automatically-unhide-macos-hidden-apps = true
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
exec-on-workspace-change = ["/bin/bash", "-c", "sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE"]
on-focus-changed = ["move-mouse window-lazy-center", "exec-and-forget sketchybar --trigger aerospace_focus_change"]
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
start-at-login = true

[gaps.inner]
horizontal = 3
vertical = 3

[gaps.outer]
bottom = 2
left = 2
right = 2
top = 45

[key-mapping]
preset = "qwerty"

[mode.main.binding]
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-comma = "layout accordion horizontal vertical"
alt-equal = "resize smart +50"
alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"
alt-minus = "resize smart -50"
alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-f = "fullscreen --no-outer-gaps"
alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"
alt-shift-semicolon = "mode service"
alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
alt-slash = "layout tiles horizontal vertical"
alt-tab = "workspace-back-and-forth"

[mode.service.binding]
alt-shift-h = ["join-with left", "mode main"]
alt-shift-j = ["join-with down", "mode main"]
alt-shift-k = ["join-with up", "mode main"]
alt-shift-l = ["join-with right", "mode main"]
b = ["balance-sizes", "mode main"]
backspace = ["close-all-windows-but-current", "mode main"]
esc = ["mode main"]
f = ["layout floating tiling", "mode main"]
r = ["flatten-workspace-tree", "mode main"]

[[on-window-detected]]
run = "move-node-to-workspace 1"

[on-window-detected.if]
app-name-regex-substring = "zen|safari|helium"

[[on-window-detected]]
run = "move-node-to-workspace 2"

[on-window-detected.if]
app-name-regex-substring = "TV|spotify|stremio"

[[on-window-detected]]
run = "move-node-to-workspace 3"

[on-window-detected.if]
app-name-regex-substring = "bluebook|preview"

[[on-window-detected]]
run = "move-node-to-workspace 4"

[on-window-detected.if]
app-name-regex-substring = "wezterm|kitty|ghostty|terminal"
