git:
  paging:
    colorArg: always
    pager: delta --paging=never --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  expandFocusedSidePanel: true
  nerdFontsVersion: '3'
  showBottomLine: false
  showPanelJumps: false
